### ISSUE TITLE
Github actions CICD

### ISSUE THREAD

**Issue by Contingency1** [modern-agile-team/ModernWorld-back#14]
## 개요
- CICD

## 작업 목록
- [ ] Github actions를 이용한 CICD 구현

## 참고
- https://mag1c.tistory.com/465#article-3--ci%EB%A5%BC-%EC%9C%84%ED%95%9C-%EC%84%A4%EC%A0%95%ED%8C%8C%EC%9D%BC-%EC%83%9D%EC%84%B1 (NestJS관련)
- https://velog.io/@sysy123/Github-Actions-CICD#2-ssh-%ED%82%A4-%EB%93%B1%EB%A1%9D

**Comment by Contingency1** [comment]
ubuntu@ip-172-31-38-179:~/actions-runner$ ./config.cmd --url https://github.com/modern-agile-team/ModernWorld-back --token BELCZ3AA3VMTR45RV2MDSKDGJQNHM./config.sh --url https://github.com/modern-agile-team/ModernWorld-back --token BELCZ3ADO276QGXUMPWJET3GJQN3K
-bash: ./config.cmd: No such file or directory
ubuntu@ip-172-31-38-179:~/actions-runner$ ./config.sh --url https://github.com/modern-agile-team/ModernWorld-back --token BELCZ3ADO276QGXUMPWJET3GJQN3K
./env.sh: line 37: .path: Permission denied
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/home/ubuntu/actions-runner/_diag/Runner_20240521-025750-utc.log' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at GitHub.Runner.Common.HostTraceListener.CreatePageLogWriter()
   at GitHub.Runner.Common.HostTraceListener..ctor(String logFileDirectory, String logFilePrefix, Int32 pageSizeLimit, Int32 retentionDays)
   at GitHub.Runner.Common.HostContext..ctor(String hostType, String logFile)
   at GitHub.Runner.Listener.Program.Main(String[] args)
./config.sh: line 81: 110005 Aborted                 (core dumped) ./bin/Runner.Listener configure "$@"
ChatGPT
System.UnauthorizedAccessException 및 Permission denied 오류는 /home/ubuntu/actions-runner/_diag/Runner_20240521-025750-utc.log 파일에 대한 접근 권한이 부족해서 발생하는 문제입니다. 이 문제를 해결하려면 해당 파일과 디렉토리에 적절한 권한을 부여해야 합니다.

다음은 이 문제를 해결하는 방법입니다:

파일과 디렉토리의 소유자를 변경합니다.
파일과 디렉토리에 적절한 권한을 부여합니다.
이를 수행하려면 다음 단계를 따라 실행하십시오:

디렉토리와 파일의 소유자 변경:
chown 명령어를 사용하여 디렉토리와 파일의 소유자를 ubuntu 사용자로 변경합니다.

bash
코드 복사
sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner
파일과 디렉토리에 적절한 권한 부여:
chmod 명령어를 사용하여 디렉토리와 파일에 적절한 권한을 부여합니다.

bash
코드 복사
sudo chmod -R 755 /home/ubuntu/actions-runner
위의 명령을 실행한 후, 다시 GitHub Actions Runner를 설정해 보세요.

전체 프로세스 요약
GitHub Actions Runner 디렉토리의 소유자를 ubuntu 사용자로 변경합니다.
GitHub Actions Runner 디렉토리에 적절한 권한을 부여합니다.
Runner를 다시 설정합니다.
실행 예시
터미널에서 다음 명령을 실행하세요:

bash
코드 복사
# Change ownership of the actions-runner directory
sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner

# Set the appropriate permissions for the actions-runner directory
sudo chmod -R 755 /home/ubuntu/actions-runner

# Re-run the config.sh script with the correct URL and token
./config.sh --url https://github.com/modern-agile-team/ModernWorld-back --token BELCZ3ADO276QGXUMPWJET3GJQN3K
이제 config.sh 스크립트를 실행하면 접근 권한 문제 없이 설정이 완료될 것입니다.


ubuntu@ip-172-31-38-179:~/actions-runner$ ./run.sh
-bash: ./run.sh: Permission denied
ChatGPT
Permission denied 오류는 run.sh 파일에 실행 권한이 없어서 발생합니다. 이를 해결하려면 chmod 명령어를 사용하여 run.sh 파일에 실행 권한을 부여해야 합니다.

다음 단계를 따라 실행하십시오:

run.sh 파일에 실행 권한을 부여합니다.
run.sh 스크립트를 실행합니다.
실행 권한 부여
bash
코드 복사
# Change to the actions-runner directory if not already in it
cd /home/ubuntu/actions-runner

# Grant execute permissions to run.sh
sudo chmod +x run.sh
스크립트 실행
bash
코드 복사
# Run the script
./run.sh
이렇게 하면 run.sh 스크립트에 실행 권한이 부여되고, 스크립트를 실행할 수 있습니다.

요약
chmod 명령어를 사용하여 run.sh 파일에 실행 권한을 부여합니다.
스크립트를 실행합니다.
이제, run.sh 파일이 제대로 실행될 것입니다.
